name: Deploy App

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3,15 * * *" # 03:00 e 15:00 UTC = 00:00 e 12:00 BRT

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Google Drive credentials
        run: echo "$GCP_SERVICE_ACCOUNT_JSON" > service_account.json
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      - name: Run the app
        run: |
          python -m app.main
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_FILE_KEY: ${{ secrets.DB_FILE_KEY }}
          LOCAL_DB_PATH: ${{ secrets.LOCAL_DB_PATH }}
          SUBREDDITS: ${{ secrets.SUBREDDITS }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
